apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver1
  name: webserver1
  namespace: task-4-res
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver1
  template:
    metadata:
      labels:
        app: webserver1
    spec:
      containers:
      - image: joseluisq/static-web-server:2.18
        name: static-web-server
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
        env:
          - name: SERVER_PORT
            value: "8080"
        securityContext:
          runAsNonRoot: false
          runAsUser: 10000
          runAsGroup: 10000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
