controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

# Please find the correct config here: https://github.com/kubernetes/ingress-nginx/tree/helm-chart-4.7.0/charts/ingress-nginx