apiVersion: v1
kind: Namespace
metadata:
  ?: demo-app-2
  labels:
    mmelab.io/task: rm-task-1
    mmelab.io/app: demo-app-2
---
apiVersion: v1
kind: ResourceQuota
?:
  name: quota
  namespace: demo-app-2
  labels:
    mmelab.io/task: rm-task-1
    mmelab.io/app: demo-app-2
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
