apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    course.ti8m.ch/task: rm-task-2
    course.ti8m.ch/app: demo-app-1
  name: demo-app-1
  namespace: demo-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      course.ti8m.ch/task: rm-task-2
      course.ti8m.ch/app: demo-app-1
  template:
    metadata:
      labels:
        course.ti8m.ch/task: rm-task-2
        course.ti8m.ch/app: demo-app-1
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
