apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    course.ti8m.ch/task: rm-task-3
    course.ti8m.ch/app: demo-app-2
  name: demo-app-2
  namespace: demo-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      course.ti8m.ch/task: rm-task-3
      course.ti8m.ch/app: demo-app-2
  template:
    metadata:
      labels:
        course.ti8m.ch/task: rm-task-3
        course.ti8m.ch/app: demo-app-2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
