apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mmelab.io/task: rm-task-3
    mmelab.io/app: demo-app-2
  name: demo-app-2
  namespace: demo-app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      mmelab.io/task: rm-task-3
      mmelab.io/app: demo-app-2
  template:
    metadata:
      labels:
        mmelab.io/task: rm-task-3
        mmelab.io/app: demo-app-2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "0.25"
            memory: "128Mi"
