
apiVersion: v1
kind: Namespace
metadata:
  name: demo-app
  labels:
    mmelab.io/app: demo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mmelab.io/app: demo-app
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      mmelab.io/app: demo-app
  template:
    metadata:
      labels:
        mmelab.io/app: demo-app
    spec:
      containers:
      - image: k8spaasclusterdesign.azurecr.io/demo-app:v0.3
        name: demo
        ports:
          - containerPort: 8080
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    mmelab.io/app: demo-app
  name: demo-app
  namespace: demo-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    mmelab.io/app: demo-app
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  labels:
    mmelab.io/app: demo-app
    release: monitoring
  namespace: demo-app
spec:
  selector:
    matchLabels:
      mmelab.io/app: ?
  endpoints:
  - port: http